pipeline:
  dco:
    group: meta
    image: algernon/drone-plugin-dco

  signature-check:
    group: meta
    image: algernon/drone-plugin-signature-check
    keys: [ 10E65DC045EABEFCC5193A26AC1E90BAC433F68F ]
    when:
      event: tag

  bootstrap:
    image: algernon/drone-language:arduino
    commands:
      - . ./.kaleidoscope-builder.conf && setup

  build:
    image: algernon/drone-language:arduino
    commands:
      - make build

  archive:
    image: vividboarder/drone-webdav
    file: output/algernon/algernon-*-g*.hex
    destination: https://banda.csillger.hu/remote.php/dav/files/algernon/Kaleidoscope/Model01-Sketch/
    username: algernon
    secrets: [webdav_password]
