pipeline:
  dco:
    group: meta
    image: algernon/drone-plugin-dco

  signature-check:
    group: meta
    image: algernon/drone-plugin-signature-check
    keys: [ 10E65DC045EABEFCC5193A26AC1E90BAC433F68F ]
    when:
      event: tag

  bootstrap:
    image: algernon/drone-language:arduino
    commands:
      - . ./.kaleidoscope-builder.conf && setup

  build:
    image: algernon/drone-language:arduino
    commands:
      - make build
