language: cpp
dist: trusty
sudo: required
os:
  - linux
before_install:
  - pushd ..
  - wget http://downloads.arduino.cc/arduino-1.6.11-linux64.tar.xz
  - tar xf arduino-1.6.11-linux64.tar.xz
  - popd
install:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - lib/KeyboardioFirmware/tools/keyboardio-builder submodule-update
script:
  - lib/KeyboardioFirmware/tools/keyboardio-builder build ARDUINO_PATH=$(pwd)/../arduino-1.6.11
